
CREATE OR REPLACE VIEW ATS_TRNSCTN_V AS
SELECT 
  distinct(log.ATS_TRNSCTN_LOG_ID) "ATS_TRNSCTN_LOG_ID",
  log.CUST_FST_NAM "CUST_FST_NAM",
  log.CUST_MID_NAM "CUST_MID_NAM",
  log.CUST_LST_NAM "CUST_LST_NAM",
  lnkg.LNKG_KY "LNKG_KY",
  log.CUST_BRTH_DT "CUST_BRTH_DT",
  log.ETS_APNTMT_ID "ETS_APNTMT_ID",
  p.PGM_NAM "PGM_NAM",
  t.TST_NAM "TST_NAM",
  var.FUNC_CDE "FUNC_CDE",
  log.APNTMT_DT "APNTMT_DT",
  var.TST_CDE "TST_CDE",
  var.DLVY_MDE_CDE "DLVY_MDE_CDE",
  o.ORG_NAM "ORG_NAM",
  log.TST_CNTR_ID_NO "TST_CNTR_ID_NO",
  country.ISO3_CNTRY_CDE "ISO3_CNTRY_CDE",
  adr.ADDRESS_LINE1 "ADDRESS_LINE1",
  adr.ADDRESS_LINE2 "ADDRESS_LINE2",
  adr.CITY "CITY",
  adr.STATE_PROV_REGION "STATE_PROV_REGION",
  ets_adr.ST_PROV_NAM "ST_PROV_NAM",
  adr.POSTAL_CODE "POSTAL_CODE",
  log.TM_ZN_OFST_QTY "TM_ZN_OFST_QTY",
  log.REGN_SYS_ID "REGN_SYS_ID",
  log.TRNSCTN_TYP_CDE "TRNSCTN_TYP_CDE",
  log.TRNSCTN_STS_TYP_CDE "TRNSCTN_STS_TYP_CDE",
  transType.TRNSCTN_TYP_DSC "TRNSCTN_TYP_DSC",
  log.BKNG_UPDATED_DATE "BKNG_UPDATED_DATE",
  '1' "APNTMT_CNT",
  'N' "MULTI_DAY_APNTMT_FLG",
  log.ETS_APNTMT_ID "FST_APNTMT_ID",
  count(bkngAccmd.ACMDTN_TYP_CDE) Over(partition by bkngAccmd.BKNG_ID) "ACMDTN_CNT",
  log.ATS_SNT_DTE "ATS_SNT_DTE",
  log.ATS_RPT_ND_FLG "ATS_RPT_ND_FLG"
FROM
  ATS_TRNSCTN_LOG log
  LEFT OUTER JOIN BKNG_ACMDTN bkngAccmd ON log.BKNG_ID = bkngAccmd.BKNG_ID
  INNER JOIN TST_VARTN var ON log.LANG_CDE = var.LANG_CDE AND log.DLVY_MDE_CDE=var.DLVY_MDE_CDE   AND log.TST_ID=var.TST_ID
  INNER JOIN ORG o ON log.TST_CNTR_ID_NO = o.ORG_ID_NO
  INNER JOIN ORG_ADR orgAdr ON o.ORG_ID_NO   = orgAdr.ORG_ID_NO
  INNER JOIN BLC_ADDRESS adr ON orgAdr.ADDRESS_ID    =adr.ADDRESS_ID
  INNER JOIN ETS_ADR ets_adr ON ets_adr.ADDRESS_ID = adr.ADDRESS_ID
  INNER JOIN ETS_CNTRY country ON adr.COUNTRY = country.cntry_cde
  INNER JOIN TRNSCTN_TYP transType ON transType.TRNSCTN_TYP_CDE = log.TRNSCTN_TYP_CDE
  INNER JOIN TST_TKR_TST testTakerTest ON testTakerTest.TST_TKR_TST_ID = log.TST_TKR_TST_ID
  INNER JOIN ETS_CUST_LNKG lnkg ON testTakerTest.CUSTOMER_ID = lnkg.CUSTOMER_ID
  INNER JOIN TST t ON t.TST_ID = var.TST_ID
  INNER JOIN PGM p ON p.PGM_CDE=t.PGM_CDE
WHERE 
  lnkg.LNKG_TYP_CDE='DSPID' AND (ATS_RPT_ND_FLG = 'Y' OR ((TRNSCTN_STS_TYP_CDE = 'ERROR' ) OR
  (TRNSCTN_STS_TYP_CDE = 'NTSNT' AND (log.EVNT_OTCM_STS_TYP_CDE = 'NCI' OR 
  ((log.EVNT_OTCM_STS_TYP_CDE = 'NOS' OR log.EVNT_OTCM_STS_TYP_CDE = 'CNT') AND (SYSDATE - CAST(BKNG_UPDATED_DATE AS DATE) > 1 AND 
  (log.BKNG_ID not in (SELECT BKNG_ID  FROM ATS_TRNSCTN_LOG a WHERE a.BKNG_ID = log.BKNG_ID group by a.BKNG_ID having count(*) > 1)))))) 
  AND ATS_RPT_ND_FLG = 'N' AND log.EVNT_OTCM_STS_TYP_CDE <> 'CHI'))
ORDER BY 
  log.BKNG_UPDATED_DATE asc;