package org.ets.ereg.domain.scheduling;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.ets.ereg.domain.interfaces.model.scheduling.TestCenterType;
import org.hibernate.annotations.Type;


/**
 * TestCenterType generated by hbm2java
 */
@Entity
@Table(name = "TST_CNTR_TYP")
public class TestCenterTypeImpl implements TestCenterType, Serializable {

	private static final long serialVersionUID = -5883693114376454747L;
	
	@Id
	@Column(name = "TST_CNTR_TYP_CDE", nullable = false, length = 5)
	private String code;

	@Column(name = "TST_CNTR_TYP_DSC", nullable = false, length = 175)
	private String description;

    @Column(name = "TST_CNTR_TYP_DSPLY_SEQ", nullable=false)
    private Long displaySequence;

    @Column(name = "DSPLY_DTA_FLG", nullable = false, columnDefinition = "char(1) default 'Y'")
    @Type(type="yes_no")
    private Boolean isDisplayable;

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#getCode()
	 */
	@Override
	public String getCode() {
		return code;
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#setCode(java.lang.String)
	 */
	@Override
	public void setCode(String code) {
		this.code=code;		
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#getDescription()
	 */
	@Override
	public String getDescription() {
		return description;
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#setDescription(java.lang.String)
	 */
	@Override
	public void setDescription(String description) {
		this.description=description;	
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#getDisplaySequence()
	 */
	@Override
	public Long getDisplaySequence() {
		return displaySequence;
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#setDisplaySequence(java.lang.Long)
	 */
	@Override
	public void setDisplaySequence(Long displaySequence) {
		this.displaySequence=displaySequence;
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#isDisplayable()
	 */
	@Override
	public Boolean isDisplayable() {
		return isDisplayable;
	}

	/* (non-Javadoc)
	 * @see org.ets.ereg.domain.interfaces.model.common.ReferenceEntityInterface#setDisplayable(java.lang.Boolean)
	 */
	@Override
	public void setDisplayable(Boolean isDisplayable) {
		this.isDisplayable=isDisplayable;		
	}  
	
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		if (obj instanceof TestCenterTypeImpl) {
			final TestCenterTypeImpl other = (TestCenterTypeImpl)obj;
			return new EqualsBuilder().append(code, other.code).append(description, other.description).isEquals();
		} else {
			return false;
		}
	}
    
}
