--------------------------------------------------------
--  File created - Wednesday-May-15-2013   
--------------------------------------------------------
REM INSERTING into LANG
SET DEFINE OFF;
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('EN','English',1,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('ES','Spanish',2,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('PO','Portuguese',3,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('RS','Russian',4,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('HI','Hindi',5,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('CH','Chinese',6,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('FR','French',7,'Y',null,null,null,null,null,null);
Insert into LANG (LANG_CDE,LANG_DSC,LANG_DSPLY_SEQ,DSPLY_DTA_FLG,CREATED_BY_ADMIN_USR_ID,CREATED_BY_CUSTOMER_ID,DATE_CREATED,UPDATED_BY_ADMIN_USR_ID,UPDATED_BY_CUSTOMER_ID,DATE_UPDATED) values ('DE','Deutsch (German)',8,'Y',null,null,null,null,null,null);
