DROP FUNCTION greatCircleDistance IF EXISTS;
CREATE FUNCTION greatCircleDistance(originLatitude DOUBLE, originLongitude DOUBLE, destinationLatitude DOUBLE, destinationLongitude DOUBLE) RETURNS DOUBLE RETURN acos(sin(originLatitude/57.2958279)*sin(destinationLatitude/57.2958279) +cos(originLatitude/57.2958279)*cos(destinationLatitude/57.2958279)*cos((destinationLongitude-originLongitude)/57.2958279))*3959;

INSERT INTO ORG_RLE_TYP (ORG_RLE_TYP_CDE, ORG_RLE_TYP_DSC, ORG_RLE_TYP_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('AGNCY', 'Agency', '2', 'N');

Insert into BLC_COUNTRY(ABBREVIATION,NAME) values('US','United States');
Insert into ETS_CNTRY(ISD_CDE,CNTRY_CDE) values('1','US');
Insert into BLC_LOCALE (LOCALE_CODE,DEFAULT_FLAG,FRIENDLY_NAME) values ('en',null,'English');
Insert into BLC_LOCALE (LOCALE_CODE,DEFAULT_FLAG,FRIENDLY_NAME) values ('es',null,'Spanish');
Insert into BLC_STATE(ABBREVIATION,NAME,COUNTRY) values('CT','Connecticut','US');
Insert into BLC_STATE(ABBREVIATION,NAME,COUNTRY) values('PA','Pennsylvania','US');
Insert into BLC_STATE(ABBREVIATION,NAME,COUNTRY) values('NJ','New Jersey','US');
Insert into BLC_STATE(ABBREVIATION,NAME,COUNTRY) values('NY','New York','US');

INSERT INTO ADR_PRPS(ADR_PRPS_CDE, ADR_PRPS_DSC, ADR_PRPS_DSPLY_SEQ) VALUES ('HOME', 'Home address', 1);

INSERT INTO DLVY_MDE (DLVY_MDE_CDE, DLVY_MDE_DSC, DLVY_MDE_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('PBT', 'Paper-Based Test', 1, 'Y');
INSERT INTO DLVY_MDE (DLVY_MDE_CDE, DLVY_MDE_DSC, DLVY_MDE_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('CBT', 'Computer-Based Test', 2, 'Y');
INSERT INTO DLVY_MDE (DLVY_MDE_CDE, DLVY_MDE_DSC, DLVY_MDE_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('ONLIN', 'Online Proctoring', 3, 'Y');
INSERT INTO DLVY_MDE (DLVY_MDE_CDE, DLVY_MDE_DSC, DLVY_MDE_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('OTHER', 'Other', 4, 'Y');

-- Insert Program Type
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('GRE','Graduate Record Examinations', 2, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('PSAT','Preliminary SAT', 1, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('CLEP','College Level Examination Program', 3, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('TOEFL','Test of English as a Foreign Language', 4, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('TOEIC','Test of English for International Communications', 5, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('TFI','Test de Fran�ais International', 6, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('PRAX','Praxis test', 7, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('NAEP','National Assessment of Educational Progress', 8, 'Y');
INSERT INTO PGM (PGM_CDE, PGM_NAM, PGM_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('HSE','High School Equivalency Test', 9, 'Y');


Insert into HIER_TYP (HIER_TYP_CDE,DSC) values ('TST','Hierarchy Test');
Insert into EREG_HIER (EREG_HIER_ID,HIER_NAM,PARNT_EREG_HIER_ID,HIER_TYP_CDE,HIER_LVL) values (1,'HSET_TEST',null,'TST',1);

INSERT INTO TST (PGM_CDE, TST_ID, DSPLY_DTA_FLG, TST_NAM,TST_DURN,SCHDLG_DURN) VALUES ('HSE', 1, 'Y', 'Mathematics',150,150);

Insert into PHONE_TYP(phone_typ_cde,phone_typ_dsc) values('M','Mobile');
Insert into PHONE_TYP(phone_typ_cde,phone_typ_dsc) values('L','Landline');

INSERT INTO SCHDLG_TYP (SCHDLG_TYP_CDE, SCHDLG_TYP_DSC, SCHDLG_TYP_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('TCAM', 'TCA Scheduling Model.', '1', 'Y');
INSERT INTO SCHDLG_TYP (SCHDLG_TYP_CDE, SCHDLG_TYP_DSC, SCHDLG_TYP_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('CANDM', 'Candidate Scheduling Model.', '2', 'Y');

INSERT INTO GLBL_TM_ZN (TM_ZN_STD_CDE, TM_ZN_STD_NAM, GLBL_TM_ZN_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('EST', 'Eastern Standard Time', '1', 'Y');
INSERT INTO GLBL_TM_ZN (TM_ZN_STD_CDE, TM_ZN_STD_NAM, GLBL_TM_ZN_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('CST', 'Central Standard Time', '2', 'Y');
INSERT INTO GLBL_TM_ZN (TM_ZN_STD_CDE, TM_ZN_STD_NAM, GLBL_TM_ZN_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('MST', 'Mountain Standard Time', '3', 'Y');
INSERT INTO GLBL_TM_ZN (TM_ZN_STD_CDE, TM_ZN_STD_NAM, GLBL_TM_ZN_DSPLY_SEQ, DSPLY_DTA_FLG) VALUES ('PST', 'Pacific Standard Time', '4', 'Y');

INSERT INTO ORG (ORG_ID_NO, ACTV_FLG, ORG_NAM, ORG_RLE_TYP_CDE) VALUES ('10000', 'Y', 'Missouri Agency', 'AGNCY');
INSERT INTO AGNCY (AGNCY_ID_NO) VALUES ('10000');
INSERT INTO AGNCY_PGM (AGNCY_ID_NO, PGM_CDE, SCHDLG_TYP_CDE) VALUES ('10000', 'HSE', 'CANDM');
INSERT INTO ORG (ORG_ID_NO, ACTV_FLG, ORG_NAM, ORG_RLE_TYP_CDE) VALUES ('10001', 'Y', 'Montana Agency', 'AGNCY');
INSERT INTO AGNCY (AGNCY_ID_NO) VALUES ('10001');
INSERT INTO AGNCY_PGM (AGNCY_ID_NO, PGM_CDE, SCHDLG_TYP_CDE) VALUES ('10001', 'HSE', 'CANDM');
INSERT INTO ORG (ORG_ID_NO, ACTV_FLG, ORG_NAM, ORG_RLE_TYP_CDE) VALUES ('10002', 'Y', 'New Hampshire Agency', 'AGNCY');
INSERT INTO AGNCY (AGNCY_ID_NO) VALUES ('10002');
INSERT INTO AGNCY_PGM (AGNCY_ID_NO, PGM_CDE, SCHDLG_TYP_CDE) VALUES ('10002', 'HSE', 'CANDM');

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (1, '1 AAA Drive Suite 202', 'Hamilton','NJ','US','08691',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(1, 'HOME', 40.205214, -74.631162);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (2, '601 Walnut Street, Curtis Center, Suite 150', 'West Philadelphia','PA','US','19106',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(2, 'HOME', 39.9493801, -75.145782);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (3, '100 Walnut Ave., suite 301', 'Clark','NJ','US','07066',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(3, 'HOME', 40.6298702, -74.3033176);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (4, '100 W. Elm Street, Suite 300', 'Conshohocken','PA','US','19428',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(4, 'HOME', 40.205214, -74.631162);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (5, '1381 Chews Landing Road, Chews Landing Commons, Bldg 5', 'Laurel Springs','NJ','US','08021',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(5, 'HOME', 39.8203474, -75.0056186);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT, EMAIL_ADDRESS) values (6, '119 West 19th St', 'New York','NY','US','10011',1,1,1,'email@testcenter.com');
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(6, 'HOME', 40.7409784,-73.9954437);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (7, '24 West 61st St', 'New York','NY','US','10023',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(7, 'HOME', 40.7699458,-73.9826457);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (8, '1011 First Ave, 6th Floor', 'New York','NY','US','10022',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(8, 'HOME', 40.7574435,-73.9635901);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (9, '31-10 Thompson Avenue', 'Long Island City','NY','US','11101',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(9, 'HOME', 40.7439510,-73.9351540);

Insert into BLC_ADDRESS (ADDRESS_ID,ADDRESS_LINE1,CITY,STATE_PROV_REGION,COUNTRY,POSTAL_CODE,IS_ACTIVE,IS_BUSINESS,IS_DEFAULT) values (10, '111 Livingston Street', 'Brooklyn','NY','US','11201',1,1,1);
Insert into ETS_ADR (ADDRESS_ID, ADR_PRPS_CDE, LTD_DEG, LNGTD_DEG) values(10, 'HOME', 40.6915878,-73.9898898);

Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (1,1,1,'9178065501');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'1','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (2,1,1,'9178065502');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'2','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (3,1,1,'9178065503');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'3','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (4,1,1,'9178065504');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'4','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (5,1,1,'9178065505');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'5','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (6,1,1,'2127274345');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'6','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (7,1,1,'2128307783');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'7','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (8,1,1,'2123711011');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values('2016','8','US','L');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (9,1,1,'7184826168');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'9','US','M');
Insert into BLC_PHONE (PHONE_ID,IS_ACTIVE,IS_DEFAULT,PHONE_NUMBER) values (10,1,1,'8562280387');
Insert into ETS_PHONE(TEL_EXTNSN_NO,PHONE_ID,CNTRY_CDE,PHONE_TYP_CDE) values(null,'10','US','M');

Insert into ORG_RLE_TYP(ORG_RLE_TYP_CDE, ORG_RLE_TYP_DSC, ORG_RLE_TYP_DSPLY_SEQ, DSPLY_DTA_FLG) values('ORLE1', 'Organization Role 1', 1, 'N');

Insert into RSTRCT_ACS_RSN(RSTRCT_ACS_RSN_CDE, RSTRCT_ACS_RSN_DSC, RSTRCT_ACS_RSN_DSPLY_SEQ, DSPLY_DTA_FLG) values('MIL', 'Military Only', 1, 'Y');

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(1, 'ORLE1', 'Prometric Testing Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(1,1);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(1,1);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(1, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(1, 'PBT');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(1, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(1, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(2, 'ORLE1', 'Prometric Testing Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(2,2);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(2,2);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(2, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(2, 'PBT');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(2, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(2, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(3, 'ORLE1', 'Prometric Testing Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(3,3);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(3,3);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(3, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(3, 'PBT');
--Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(3, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(3, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(4, 'ORLE1', 'Prometric Testing Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(4,4);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(4,4);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(4, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(4, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(4, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(5, 'ORLE1', 'Pro-metric Testing Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(5,5);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(5,5);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(5, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(5, 'PBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(5, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG, WEB_URL) values(6, 'ORLE1', 'FEDCAP', 'Y', 'www.testcenter.com');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(6,6);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(6,6);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG, RSTRCT_ACS_RSN_CDE, OFC_HR_TXT, SPCL_DRV_DIRCTN_TXT, SPCL_ON_SITE_DIRCTN_TXT) values(6, 'Y', 'MIL', 'Monday - Friday : 9:00 AM - 5:00 PM\nSaturday, Sunday: Closed','Drive rashly','Drive carefully');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(6, 'PBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(6, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(7, 'ORLE1', 'Chelsea Recreation Center', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(7,7);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(7,7);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(7, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(7, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(7, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(8, 'ORLE1', 'Catholic Guild for the Blind', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(8,8);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(8,8);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(8, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(8, 'PBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(8, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(9, 'ORLE1', 'Laguardia Community College', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(9,9);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(9,9);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG) values(9, 'N');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(9, 'PBT');
Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(9, 'CBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(9, 'HSE', 10000);

Insert into ORG(ORG_ID_NO, ORG_RLE_TYP_CDE, ORG_NAM, ACTV_FLG) values(10, 'ORLE1', 'SUNY - Brooklyn EOC', 'Y');
Insert into ORG_ADR(ORG_ID_NO, ADDRESS_ID) values(10,10);
Insert into ORG_PHONE(ORG_ID_NO, PHONE_ID) values(10,10);
Insert into TST_CNTR(TST_CNTR_ID_NO, RSTRCT_ACS_FLG, TM_ZN_STD_CDE) values(10, 'N', 'CST');
--Insert into TST_CNTR_DLVY_MDE(TST_CNTR_ID_NO, DLVY_MDE_CDE) values(10, 'PBT');
Insert into TST_CNTR_PGM(TST_CNTR_ID_NO, PGM_CDE, AGNCY_ID_NO) values(10, 'HSE', 10000);


INSERT INTO BLC_ADMIN_ROLE (ADMIN_ROLE_ID, DESCRIPTION, NAME) VALUES (7,'TCA','ROLE_TEST_CENTER_ADMIN');
INSERT INTO BLC_ADMIN_USER (ADMIN_USER_ID, ACTIVE_STATUS_FLAG, EMAIL, LOGIN, NAME, PASSWORD) VALUES (112, 1, 'test@ets.org', 'test', 'test', 'password');
INSERT INTO BLC_ADMIN_USER_ROLE_XREF (ADMIN_ROLE_ID, ADMIN_USER_ID) VALUES (7, 112);
INSERT INTO ETS_ADM_USR (ADMIN_USER_ID, FIRST_NAME, LAST_NAME, MID_NAM) VALUES (112,'test', 'test','');
insert into TST_CNTR_ADMIN(ADMIN_USER_ID,TST_CNTR_ID_NO)values(112,1);
insert into TST_CNTR_ADMIN(ADMIN_USER_ID,TST_CNTR_ID_NO)values(112,2);
insert into TST_CNTR_ADMIN(ADMIN_USER_ID,TST_CNTR_ID_NO)values(112,3);

insert into TST_STS_TYP(TST_STS_TYP_CDE,TST_STS_TYP_DSC, DSPLY_DTA_FLG) values('SCDL','SCHEDULED','Y');
insert into TST_STS_TYP(TST_STS_TYP_CDE,TST_STS_TYP_DSC, DSPLY_DTA_FLG) values('RSCDL','RESCHEDULED','Y');
insert into FRM_TYP(FRM_TYP_CDE,FRM_TYP_DSC,DSPLY_DTA_FLG) values('TEST','TEST','Y');
insert into FRM_TYP(FRM_TYP_CDE,FRM_TYP_DSC,DSPLY_DTA_FLG) values('BASE','BASE','Y');
insert into LANG(LANG_CDE,LANG_DSC,DSPLY_DTA_FLG) values('EN','english','Y');
insert into BKNG_STS_TYP(BKNG_STS_TYP_CDE,BKNG_STS_TYP_DSC,DSPLY_DTA_FLG) values('RSRVD','RESERVED','Y');
insert into BKNG_STS_TYP(BKNG_STS_TYP_CDE,BKNG_STS_TYP_DSC,DSPLY_DTA_FLG) values('CNCL','CANCELED','Y');
insert into BLC_CHALLENGE_QUESTION(QUESTION_ID,QUESTION) values(1,'What is your favourite sports team?');
Insert into GNDR(GNDR_CDE,GNDR_DSC) values('M','Male');
Insert into GNDR(GNDR_CDE,GNDR_DSC) values('F','Female');
Insert into ETS_CUST_TYP (CUST_TYP_CDE,CUST_TYP_DSC) values ('cu','Customer');
Insert into ETS_CUST_TYP (CUST_TYP_CDE,CUST_TYP_DSC) values ('STUD','Student');
insert into BLC_CUSTOMER (CUSTOMER_ID,CHALLENGE_ANSWER,DEACTIVATED,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,PASSWORD,PASSWORD_CHANGE_REQUIRED,RECEIVE_EMAIL,IS_REGISTERED,USER_NAME,CHALLENGE_QUESTION_ID,LOCALE_CODE) values (1,'Something',0,'akovuri@ets.org','Arvind','Kovuri','house23',0,0,1,'akovuri',1,'en');
insert into ETS_CUST (TRMS_ACEPTNC_DTM,BRTH_DTE,GNDR_CDE,MID_NAM,PRFRD_TST_TAKING_LANG_CDE,PRMRY_SPKNG_LANG_CDE,SSN_LST_4,SRC_ID,CUSTOMER_ID,CUST_TYP_CDE,ETNCTY_CDE,MIL_STS_CDE) values (null,to_date('09-10-1983','DD-MM-YYYY'),'M','K',null,null,'7828',null,1,'cu',null,null);

INSERT INTO TST (PGM_CDE, TST_ID, DSPLY_DTA_FLG, TST_NAM,TST_DURN,SCHDLG_DURN) VALUES ('HSE', 2, 'Y', 'ELA-Writing (MC Section)',150,150);
INSERT INTO TST (PGM_CDE, TST_ID, DSPLY_DTA_FLG, TST_NAM,TST_DURN,SCHDLG_DURN) VALUES ('HSE', 3, 'Y', 'ELA-Writing (CR Section)',150,150);
INSERT INTO TST (PGM_CDE, TST_ID, DSPLY_DTA_FLG, TST_NAM,TST_DURN,SCHDLG_DURN) VALUES ('HSE', 4, 'Y', 'Social Studies',150,150);
INSERT INTO TST (PGM_CDE, TST_ID, DSPLY_DTA_FLG, TST_NAM,TST_DURN,SCHDLG_DURN) VALUES ('HSE', 5, 'Y', 'Science',150,150);

insert into TST_VARTN(TST_ID,LANG_CDE,DLVY_MDE_CDE,SCHDLG_TST_CDE,TST_CDE) values (1,'EN','PBT','900','MATH');
insert into TST_VARTN(TST_ID,LANG_CDE,DLVY_MDE_CDE,SCHDLG_TST_CDE,TST_CDE) values (2,'EN','CBT','901','ELAD');
insert into TST_VARTN(TST_ID,LANG_CDE,DLVY_MDE_CDE,SCHDLG_TST_CDE,TST_CDE) values (3,'EN','CBT','902','ELARD');
insert into TST_VARTN(TST_ID,LANG_CDE,DLVY_MDE_CDE,SCHDLG_TST_CDE,TST_CDE) values (4,'EN','CBT','903','SST');
insert into TST_VARTN(TST_ID,LANG_CDE,DLVY_MDE_CDE,SCHDLG_TST_CDE,TST_CDE) values (5,'EN','PBT','904','SCEIN');

insert into TST_TKR_TST(TST_TKR_TST_ID,TST_STS_TYP_CDE,CUSTOMER_ID) values(1,'SCDL',1);
insert into FRM(FRM_ID,TST_ID,EFF_DTE,FRM_DSC,FRM_CDE,FRM_TYP_CDE,EXPRTN_DTE,LANG_CDE,DLVY_MDE_CDE) values(1,1,to_date('01-01-2013','DD-MM-YYYY'),'FORM A','FORMA','BASE',to_date('31-12-2013','DD-MM-YYYY'),'EN','PBT');
insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 7 DAY),1,-4,'RSRVD',1,1,10,1,'EN','PBT');

-- Booking data
insert into BLC_CUSTOMER (CUSTOMER_ID,CHALLENGE_ANSWER,DEACTIVATED,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,PASSWORD,PASSWORD_CHANGE_REQUIRED,RECEIVE_EMAIL,IS_REGISTERED,USER_NAME,CHALLENGE_QUESTION_ID,LOCALE_CODE) values (2,'Something',0,'test@testmail.org','testFirstName','testLastName','testpass',0,0,1,'testuser',1,'en');
insert into ETS_CUST (TRMS_ACEPTNC_DTM,BRTH_DTE,GNDR_CDE,MID_NAM,PRFRD_TST_TAKING_LANG_CDE,PRMRY_SPKNG_LANG_CDE,SSN_LST_4,SRC_ID,CUSTOMER_ID,CUST_TYP_CDE,ETNCTY_CDE,MIL_STS_CDE) values (null,to_date('09-10-1980','DD-MM-YYYY'),'F','t',null,null,'7828',null,2,'cu',null,null);

insert into TST_TKR_TST(TST_TKR_TST_ID,TST_STS_TYP_CDE,CUSTOMER_ID) values(2,'SCDL',2);
insert into FRM(FRM_ID,TST_ID,EFF_DTE,FRM_DSC,FRM_CDE,FRM_TYP_CDE,EXPRTN_DTE,LANG_CDE,DLVY_MDE_CDE) values(2,3,to_date('01-01-2013','DD-MM-YYYY'),'FORM A','FORMA','BASE',to_date('31-12-2013','DD-MM-YYYY'),'EN','PBT');
insert into FRM(FRM_ID,TST_ID,EFF_DTE,FRM_DSC,FRM_CDE,FRM_TYP_CDE,EXPRTN_DTE,LANG_CDE,DLVY_MDE_CDE) values(3,3,to_date('01-01-2013','DD-MM-YYYY'),'FORM A','FORMA','BASE',to_date('31-12-2013','DD-MM-YYYY'),'EN','PBT');
insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 8 DAY),2,-4,'RSRVD',2,2,10,1,'EN','PBT');


insert into TST_TKR_TST(TST_TKR_TST_ID,TST_STS_TYP_CDE,CUSTOMER_ID) values(3,'SCDL',2);

insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 7 DAY),3,-4,'RSRVD',3,2,10,1,'EN','PBT');

insert into TST_TKR_TST(TST_TKR_TST_ID,TST_STS_TYP_CDE,CUSTOMER_ID) values(4,'SCDL',2);

insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 7 DAY),4,-4,'CNCL',3,4,10,1,'EN','PBT');
insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 8 DAY),5,-4,'CNCL',3,4,10,1,'EN','PBT');
insert into BKNG(APNTMT_DT,BKNG_ID,TM_ZN_OFST_QTY,BKNG_STS_TYP_CDE,FRM_ID,TST_TKR_TST_ID,TST_CNTR_ID_NO,TST_ID,LANG_CDE,DLVY_MDE_CDE) values((CURRENT_DATE + 1 DAY),6,-4,'RSRVD',3,4,10,1,'EN','PBT');

--Booking Accommodation Test
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('1','Extended Time',1);
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('2','Color Contrast',2);
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('3','Large Font/Magnification',3);
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('4','Audio Version',4);
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('5','Braille',5);
insert into ACMDTN_TYP(acmdtn_typ_cde,ACMDTN_TYP_DSC,ACMDTN_TYP_DSPLY_SEQ) values ('6','Large Print',6);

insert into ACMDTN_TYP_VAL(ACMDTN_TYP_VAL_ID_NO,ACMDTN_TYP_VAL_DSPLY_SEQ,ACMDTN_TYP_VAL_UI_TXT,DSPLY_DTA_FLG,LBL,SCHDLG_SVC_ACMDTN_VAL,VAL,ACMDTN_TYP_CDE) values (1,1,null,'Y','25%','EXTENDED TIME','125%','1');
insert into ACMDTN_TYP_VAL(ACMDTN_TYP_VAL_ID_NO,ACMDTN_TYP_VAL_DSPLY_SEQ,ACMDTN_TYP_VAL_UI_TXT,DSPLY_DTA_FLG,LBL,SCHDLG_SVC_ACMDTN_VAL,VAL,ACMDTN_TYP_CDE) values (2,2,null,'Y','50%','EXTENDED TIME','150%','1');
insert into ACMDTN_TYP_VAL(ACMDTN_TYP_VAL_ID_NO,ACMDTN_TYP_VAL_DSPLY_SEQ,ACMDTN_TYP_VAL_UI_TXT,DSPLY_DTA_FLG,LBL,SCHDLG_SVC_ACMDTN_VAL,VAL,ACMDTN_TYP_CDE) values (3,3,null,'Y','75%','EXTENDED TIME','175%','1');
insert into ACMDTN_TYP_VAL(ACMDTN_TYP_VAL_ID_NO,ACMDTN_TYP_VAL_DSPLY_SEQ,ACMDTN_TYP_VAL_UI_TXT,DSPLY_DTA_FLG,LBL,SCHDLG_SVC_ACMDTN_VAL,VAL,ACMDTN_TYP_CDE) values (4,4,null,'Y','100%','EXTENDED TIME','200%','1');


insert into BKNG_ACMDTN(ACMDTN_TYP_CDE, BKNG_ID, APRVD_DTE, EXPRTN_DTE, ACMDTN_TYP_VAL_ID_NO, OTHR_ACMDTN_TYP_TXT) values (1, 1, (CURRENT_DATE - 30 DAY), (CURRENT_DATE + 365 DAY), 1, 'Test');
insert into BKNG_ACMDTN(ACMDTN_TYP_CDE, BKNG_ID, APRVD_DTE, EXPRTN_DTE, ACMDTN_TYP_VAL_ID_NO, OTHR_ACMDTN_TYP_TXT) values (2, 1, (CURRENT_DATE - 30 DAY), (CURRENT_DATE + 365 DAY), 2, 'Test');

--insert Application Configuration
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (1,'generatePasswordIdentifier', 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*^+=');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (2,'startUpperCaseLetter', 'A');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (3,'endUpperCaseLetter', 'Z');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (4,'startLowerCaseLetter', 'a');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (5,'endLowerCaseLetter', 'z');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (6,'startNumber', '0');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (7,'endNumber', '9');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (8,'randomUpperCaseLength', '2');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (9,'randomLowerCaseLength', '3');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (10,'randomNumberLength', '2');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (11,'randomSpecialCaseLength', '1');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (12,'AUTH_MECHANISM', 'DATABASE');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (13,'AUTH_URL', '/j_spring_security_check');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (14,'FIELDNAME_USENAME', 'j_username');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (15,'FIELDNAME_PASSWORD', 'j_password');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (16,'HELPDESK_EMAIL', 'eReg_Developers@ets.org');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (17,'MAX_RESULTS', '100');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (18,'MAX_TESTCENTER_SEARCH_RESULTS', '100');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (19,'SEARCH_DISTANCES', '5,10,20,50,100,200,500');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (20,'randomCBTNumberLength', '16');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (21,'randomPBTNumberLength', '7');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (22,'HSE_DEFAULT_APPT_DISPLAY_COUNT', '3');

--adding for SSA integration
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) VALUES (23,'ssaLoginPwd','1qaz@WSX');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (24, 'ssaLoginUserId', 'intSysiSERdev');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (25, 'ssaAuthPort', '4040');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (26, 'ssaAuthHost', 'etsvln025');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (27, 'ssaConnTimeout', '5000');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (28, 'ssaSocketTimeout', '60000');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (29, 'ssaAcceptAllCerts', 'YES');

INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (30, 'ssaProtocol', 'http');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (31, 'ssaURL', 'etsvln025:4040/SSAWeb/intSchedulingXMLService.do');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (32, 'ssaSourceSystem', 'ERS');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (33, 'ssaRequestingSystem', 'ERS');
INSERT INTO ETS_APLCTN_CNFGN (ID, NAM, VAL) values (34, 'ssaTransactionIdPrefix', '1224250207');

Insert into EVNT_OTCM_STS_TYP (EVNT_OTCM_STS_TYP_CDE,EVNT_OTCM_STS_TYP_DSC,DSPLY_DTA_FLG,EVNT_OTCM_STS_TYP_DSPLY_SEQ,FRM_USED_FLG) values ('NCI','Not Checked In','Y',1,'N');
Insert into EVNT_OTCM_STS_TYP (EVNT_OTCM_STS_TYP_CDE,EVNT_OTCM_STS_TYP_DSC,DSPLY_DTA_FLG,EVNT_OTCM_STS_TYP_DSPLY_SEQ,FRM_USED_FLG) values ('NOS','No Show','Y',2,'N');
Insert into EVNT_OTCM_STS_TYP (EVNT_OTCM_STS_TYP_CDE,EVNT_OTCM_STS_TYP_DSC,DSPLY_DTA_FLG,EVNT_OTCM_STS_TYP_DSPLY_SEQ,FRM_USED_FLG) values ('CHI','Checked In','Y',3,'Y');
Insert into EVNT_OTCM_STS_TYP (EVNT_OTCM_STS_TYP_CDE,EVNT_OTCM_STS_TYP_DSC,DSPLY_DTA_FLG,EVNT_OTCM_STS_TYP_DSPLY_SEQ,FRM_USED_FLG) values ('CNT','Could Not Test','Y',4,'N');
