/** --------------------------------------------------------------------------
 * �2013 Educational Testing Service. All Rights Reserved.
 *
 * CONFIDENTIAL BUSINESS INFORMATION
 *
 * THIS PROGRAM IS PROPRIETARY INFORMATION OF EDUCATIONAL TESTING SERVICE AND
 * IS NOT TO BE COPIED, REPRODUCED, LENT, OR DISPOSED OF, NOR USED FOR ANY
 * PURPOSE OTHER THAN THAT WHICH IT IS SPECIFICALLY PROVIDED WITHOUT THE WRITTEN
 * PERMISSION OF THE SAID COMPANY
 * --------------------------------------------------------------------------
 * Created on Mar 25, 2013 2:06:22 PM by Hibernate Tools 3.2.4.GA
 */
package org.ets.ereg.domain.interfaces.model.rule.id;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EregHierarchyRuleSetConfigurationId generated by hbm2java
 */
@Embeddable
public class EregHierarchyRuleSetConfigurationId  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	



	
	    @Column(name="RUL_SET_CNFGN_ID", nullable=false)
	private Long ruleSetConfigurationIdentifier;


	
	    @Column(name="EREG_HIER_ID", nullable=false)
	private Long eregHierarchyIdentifier;

   
    public Long getRuleSetConfigurationIdentifier() {
        return this.ruleSetConfigurationIdentifier;
    }
    
    public void setRuleSetConfigurationIdentifier(Long ruleSetConfigurationIdentifier) {
        this.ruleSetConfigurationIdentifier = ruleSetConfigurationIdentifier;
    }
    public Long getEregHierarchyIdentifier() {
        return this.eregHierarchyIdentifier;
    }
    
    public void setEregHierarchyIdentifier(Long eregHierarchyIdentifier) {
        this.eregHierarchyIdentifier = eregHierarchyIdentifier;
    }


   public boolean equals(Object other) {
         if ( (this == other ) )
         {
        	 return true;
         }
		 if ( (other == null ) ) 
		 {
			 return false;
		 }
		 if ( !(other instanceof EregHierarchyRuleSetConfigurationId) ) 
		 {
			 return false;
		 }
		 EregHierarchyRuleSetConfigurationId castOther = ( EregHierarchyRuleSetConfigurationId ) other; 
         
		 return ((this.getRuleSetConfigurationIdentifier().equals(castOther.getRuleSetConfigurationIdentifier())) || ( this.getRuleSetConfigurationIdentifier()!=null && castOther.getRuleSetConfigurationIdentifier()!=null && this.getRuleSetConfigurationIdentifier().equals(castOther.getRuleSetConfigurationIdentifier())))
 && ((this.getEregHierarchyIdentifier().equals(castOther.getEregHierarchyIdentifier())) || ( this.getEregHierarchyIdentifier()!=null && castOther.getEregHierarchyIdentifier()!=null && this.getEregHierarchyIdentifier().equals(castOther.getEregHierarchyIdentifier())));
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuleSetConfigurationIdentifier() == null ? 0 : this.getRuleSetConfigurationIdentifier().hashCode() );
         result = 37 * result + ( getEregHierarchyIdentifier() == null ? 0 : this.getEregHierarchyIdentifier().hashCode() );
         return result;
   }   

}
