/** --------------------------------------------------------------------------
 * �2013 Educational Testing Service. All Rights Reserved.
 *
 * CONFIDENTIAL BUSINESS INFORMATION
 *
 * THIS PROGRAM IS PROPRIETARY INFORMATION OF EDUCATIONAL TESTING SERVICE AND
 * IS NOT TO BE COPIED, REPRODUCED, LENT, OR DISPOSED OF, NOR USED FOR ANY
 * PURPOSE OTHER THAN THAT WHICH IT IS SPECIFICALLY PROVIDED WITHOUT THE WRITTEN
 * PERMISSION OF THE SAID COMPANY
 * --------------------------------------------------------------------------
 * Created on Mar 25, 2013 2:06:22 PM by Hibernate Tools 3.2.4.GA
 */
package org.ets.ereg.domain.interfaces.model.rule.id;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RuleAllowableParameterId generated by hbm2java
 */
@Embeddable
public class RuleAllowableParameterId  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	



	
	    @Column(name="RUL_CDE", nullable=false, length=20)
	private String ruleCode;


	
	    @Column(name="RUL_PARM_CDE", nullable=false, length=3)
	private String ruleParameterCode;

   
    public String getRuleCode() {
        return this.ruleCode;
    }
    
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }
    public String getRuleParameterCode() {
        return this.ruleParameterCode;
    }
    
    public void setRuleParameterCode(String ruleParameterCode) {
        this.ruleParameterCode = ruleParameterCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) 
         { 
        	 return true; 
         }
		 if ( (other == null ) )
		 {
			 return false;
		 }
		 if ( !(other instanceof RuleAllowableParameterId) )
		 {
			 return false;
		 }
		 RuleAllowableParameterId castOther = ( RuleAllowableParameterId ) other; 
         
		 return ( (this.getRuleCode()==castOther.getRuleCode()) || ( this.getRuleCode()!=null && castOther.getRuleCode()!=null && this.getRuleCode().equals(castOther.getRuleCode()) ) )
 && ( (this.getRuleParameterCode()==castOther.getRuleParameterCode()) || ( this.getRuleParameterCode()!=null && castOther.getRuleParameterCode()!=null && this.getRuleParameterCode().equals(castOther.getRuleParameterCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRuleCode() == null ? 0 : this.getRuleCode().hashCode() );
         result = 37 * result + ( getRuleParameterCode() == null ? 0 : this.getRuleParameterCode().hashCode() );
         return result;
   }   

}
