UPDATE ETS_APLCTN_CNFGN SET VAL = 'OAM' WHERE ID = '12' AND NAM ='AUTH_MECHANISM';
UPDATE ETS_APLCTN_CNFGN SET VAL = '/access/oblix/apps/webgate/bin/webgate.so' WHERE ID = '13' AND NAM ='AUTH_URL';
UPDATE ETS_APLCTN_CNFGN SET VAL = 'username' WHERE ID = '14' AND NAM ='FIELDNAME_USENAME';
UPDATE ETS_APLCTN_CNFGN SET VAL = 'password' WHERE ID = '15' AND NAM ='FIELDNAME_PASSWORD';