DROP user &1 cascade;
  CREATE USER &1
  IDENTIFIED BY &2
  DEFAULT TABLESPACE &3
  TEMPORARY TABLESPACE TEMP
  ACCOUNT UNLOCK;
  -- 2 Roles for &1 
  GRANT RESOURCE TO &1;
  GRANT CONNECT TO &1;
  ALTER USER &1 DEFAULT ROLE ALL;
    -- 3 System Privileges for &1 
  GRANT CREATE VIEW TO &1;
  GRANT CREATE TABLE TO &1;
  GRANT UNLIMITED TABLESPACE TO &1;
  GRANT CREATE MATERIALIZED VIEW TO &1;
  GRANT CREATE SESSION TO &1;
  GRANT SELECT ANY DICTIONARY TO &1;
  GRANT CREATE ANY SYNONYM TO &1;
  GRANT EXECUTE ON SYS.DBMS_RANDOM TO &1;
  GRANT IMP_FULL_DATABASE TO &1; 

exit